services:
    kafka:
        image: apache/kafka:4.1.0
        container_name: kafka

        ports:
            - "9092:9092"

        env_file:
            - ./.env

    kafka_ui:
        image: provectuslabs/kafka-ui:latest
        container_name: kafka_ui

        ports:
            - "8080:8080"

        env_file:
            - ./.env
        
        depends_on:
            - kafka


    schema_registry:
        image: confluentinc/cp-schema-registry:7.5.0
        container_name: schema-registry
        
        ports:
            - "8081:8081"

        depends_on:
            - kafka
    
    
    redis:
        image: redis:8.0.3-alpine
        container_name: redis
        
        ports:
            - "6379:6379"
        
        restart: unless-stopped


    web_orders:
        build: ./orders
        container_name: web_orders

        ports:
            - "8001:8000"

        env_file:
            - ./orders/.env

        develop:
            watch:
                - action: sync
                  path: ./orders/src
                  target: /orders/src
                  ignore:
                      - .venv/

                - action: rebuild
                  path: ./orders/uv.lock
        
        depends_on:
            - kafka
            - schema_registry
            - redis

    
    web_payment:
        build: ./payment
        container_name: web_payment

        ports:
            - "8002:8000"

        env_file:
            - ./payment/.env

        develop:
            watch:
                - action: sync
                  path: ./payment/src
                  target: /payment/src
                  ignore:
                      - .venv/

                - action: rebuild
                  path: ./payment/uv.lock
        
        depends_on:
            - kafka
            - schema_registry
            - redis
    
    
    web_shipping:
        build: ./shipping
        container_name: web_shipping

        ports:
            - "8003:8000"

        env_file:
            - ./shipping/.env

        develop:
            watch:
                - action: sync
                  path: ./shipping/src
                  target: /shipping/src
                  ignore:
                      - .venv/

                - action: rebuild
                  path: ./shipping/uv.lock
        
        depends_on:
            - kafka
            - schema_registry
            - redis
    
    
    web_notifications:
        build: ./notifications
        container_name: web_notifications

        ports:
            - "8004:8000"

        env_file:
            - ./notifications/.env

        develop:
            watch:
                - action: sync
                  path: ./notifications/src
                  target: /notifications/src
                  ignore:
                      - .venv/

                - action: rebuild
                  path: ./notifications/uv.lock
        
        depends_on:
            - kafka
            - schema_registry
            - redis
